# config 작성법
# ㄴsave_path: 추론 결과 저장 위치(str)
#   weight_path: 학습 파일 위치(str)
#   data_path: 사용할 데이터셋 경로(str) 
#   data_resize: 모델 input에 맞는 크기(list)
#   model_type: 모델 타입(str)
#   platform_type: 프레임워크 타입(str)
#   data_type: 데이터셋 타입(str)
#   explain_type: 설명방식 타입(str)
#   target_layer: 어느레이어에 지정할지(list or None or dict) -> CAM 알고리즘에 해당
# model_type, platform_type, data_type, explain_type은 대소문자 상관 X

project:
  save_path: D:\\
  weight_path: D:\\3852.weights
  cfg_path: D:\\3852.cfg
  data_path: D:\\dataset\\military_data\\military_data\\107mm\\
  data_resize: [640,640]
  model_name: yolov4
  framework: darknet
  source: local
  repo_or_dir: AlexeyAB/darknet
  cache_or_local: D:\\KonanXAI_implement_darknet\\xai_darknet\\
  data_type: CUSTOM
  explain_algorithm: 
    - GradCAM:
      - target_layer: None