# config 작성법
# ㄴsave_path: 추론 결과 저장 위치(str)
#   weight_path: 학습 파일 위치(str)
#   data_path: 사용할 데이터셋 경로(str) 
#   data_resize: 모델 input에 맞는 크기(list)
#   model_type: 모델 타입(str)
#   platform_type: 프레임워크 타입(str)
#   data_type: 데이터셋 타입(str)
#   explain_type: 설명방식 타입(str)
#   target_layer: 어느레이어에 지정할지(list or None or dict) -> CAM 알고리즘에 해당
# model_type, platform_type, data_type, explain_type은 대소문자 상관 X

project:
  project_type: 'explain'
  save_path: "./heatmap/"
  weight_path: "./resnet50-0676ba61.pth"
  cfg_path: None
  data_path: "./data"
  data_resize: [224,224]
  model_name: resnet50
  framework: torch
  source: torchvision
  repo_or_dir: None
  cache_or_local: cache
  data_type: CUSTOM
  explain_algorithm: 
    - LRP:
      - rule: Epslion