# config 작성법
#   project_type: explain, train(str)
#   save_path: 추론 결과 저장 위치(str)
#   weight_path: 학습 파일 위치(str)
#   cfg_path: yaml or cfg 경로(str)
#   data_resize: 모델 input에 맞는 크기(list or tuple)
#   model_name: 모델 이름(str)
#   framework: 프레임워크 타입(str)
#   source: github, local 선택
#   repo_or_dir: 모델파일들이 저장되어있는 경로
#   cache_or_local: cache, local 선택(cache일 경우 .cache파일에 저장)
#   data_type: 데이터셋 타입(str)
#   explain_algorithm: 설명방식 타입(str)
#   target_layer: 어느레이어에 지정할지(list or None or dict) -> CAM 알고리즘에 해당
#   transfer_weights: 전이학습 사용 여부(경로 or ~(None))

head:
  project_type: 'train'
  save_path: "./checkpoint"
  weight_path: ~
  cfg_path: ~
  data_resize: [224,224]
  data_path: "D:/Datasets/ai_fire/train_lite"
  model_name: resnet50
  framework: torch
  source: torchvision
  repo_or_dir: ~
  cache_or_local: cache
  data_type: AI_FIRE
  
train:
  epoch: 10
  learning_rate: 0.0001
  batch_size: 64
  optimizer: 'adam'
  loss_function: 'CrossEntropyLoss'
  save_step: 1
  improvement_algorithm: { 
    algorithm: ABN,
    transfer_weights: "./checkpoint/Default_ResNet_AI_FIRE_20ep.pt",
    gpu_count: 3
  }